version: '3'

services:
  mysqldb:
    image: "mysql:latest"
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    restart: always
    env_file:
      - mysql_env_vars.env